import type { Meta, StoryObj } from "@storybook/react";
import { Input } from "./Input";
declare const meta: Meta<typeof Input>;
export default meta;
type Story = StoryObj<typeof meta>;
export declare const Default: Story;
export declare const Success: Story;
export declare const Warning: Story;
export declare const Input1: Story;
export declare const Error: Story;
